sudo: required

services:
  - docker

before-install:
  - docker build -t azuch/frontend -f Dockerfile.dev .

script: 
  - docker run -e CI=true azuch/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-452931296318"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"